<?php

/**
 * @file
 * Install, update and uninstall functions.
 */

declare(strict_types=1);

use Drupal\ebr_accommodation_easybooking\Entity\AccommodationEasybooking;
use Drupal\ebr\Entity\WidgetableInterface;

/**
 * Implements hook_install().
 */
function ebr_accommodation_easybooking_install(): void {
  $repo = \Drupal::service('entity_display.repository');

  foreach (AccommodationEasybooking::getDefaultWidgets() as $widgetType) {
    $repo->getViewDisplay('node', AccommodationEasybooking::BUNDLE_ROOM, 'full')
      ->setComponent(WidgetableInterface::WIDGET_FIELD_PREFIX . $widgetType, [
        'region' => 'content',
      ])->save();
  }
}

/**
 * Move all configuration to ebr_accommodation_easybooking.settings
 */
function ebr_accommodation_easybooking_update_10001(array &$sandbox): ?string {
  $oldConfig = \Drupal::configFactory()->getEditable('system.site');
  if (!empty($oldConfig->get('easybooking.info_link'))) {
    $newConfig = \Drupal::configFactory()->getEditable('ebr_accommodation_easybooking.settings');
    $newConfig->set('info_link', $oldConfig->get('easybooking.info_link'));
    $newConfig->set('customer_id', $oldConfig->get('easybooking.customer_id'));
    $newConfig->set('serial_nr', $oldConfig->get('easybooking.serial_nr'));
    $newConfig->save();
  }
  $oldConfig->clear('easybooking');
  $oldConfig->save();
  return NULL;
}

