<?php

/**
 * @file
 * Install, update and uninstall functions.
 */

declare(strict_types = 1);

use Drupal\ebr_accommodation_easybooking\Entity\AccommodationEasybooking;
use Drupal\ebr\Entity\WidgetableInterface;

/**
 * Implements hook_install().
 */
function ebr_accommodation_easybooking_install(): void {
  $repo = \Drupal::service('entity_display.repository');

  foreach (AccommodationEasybooking::getDefaultWidgets() as $widgetType) {
    $repo->getViewDisplay('node', AccommodationEasybooking::BUNDLE_ROOM, 'full')
      ->setComponent(WidgetableInterface::WIDGET_FIELD_PREFIX . $widgetType, [
        'region' => 'content',
      ])->save();
  }
}

/**
 * Implements hook_uninstall().
 */
function ebr_accommodation_easybooking_uninstall(): void {
  $config = \Drupal::configFactory()->getEditable('system.site');
  $config->clear('easybooking');
  $config->save(TRUE);
}
