<?php

declare(strict_types=1);

use Drupal\ebr_accommodation\Entity\AccommodationBase;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\Entity\BaseFieldOverride;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\ebr\EntityBusinessrules;
use Drupal\ebr\Entity\ActionableInterface;

function ebr_accommodation_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['node'][AccommodationBase::BUNDLE_ROOM])) {
    $bundles['node'][AccommodationBase::BUNDLE_ROOM]['class'] = AccommodationBase::class;
  }
  if (isset($bundles['node'][AccommodationBase::BUNDLE_PACKAGE])) {
    $bundles['node'][AccommodationBase::BUNDLE_PACKAGE]['class'] = AccommodationBase::class;
  }
}

function ebr_accommodation_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) {
  $fields = [];

  if (
    $entity_type->id() == 'node' &&
    in_array($bundle, [AccommodationBase::BUNDLE_PACKAGE, AccommodationBase::BUNDLE_ROOM]) &&
    !empty($base_field_definitions[EntityBusinessrules::FIELD_REMOTE_DATASOURCE])
  ) {
    $field = BaseFieldOverride::createFromBaseFieldDefinition($base_field_definitions[EntityBusinessrules::FIELD_REMOTE_DATASOURCE], $bundle);
    $field->setDefaultValue(AccommodationBase::DATASOURCE);
    $field->setDescription(t('If value is not empty, rooms and packages with an remote_id receive a booking link.'));
    $fields[EntityBusinessrules::FIELD_REMOTE_DATASOURCE] = $field;

    foreach (AccommodationBase::getDefaultActions() as $actionId) {
      $fields[ActionableInterface::ACTION_FIELD_PREFIX . $actionId] = BaseFieldDefinition::create('action_link')
        ->setName(ActionableInterface::ACTION_FIELD_PREFIX . $actionId)
        ->setLabel(t('Action link @type', ['@type' => AccommodationBase::getDefaultActionLabel($actionId)]))
        ->setComputed(TRUE)
        ->setClass('\Drupal\ebr\Plugin\Field\SingleComputedItemList')
        ->setSettings([
          'action_type' => $actionId,
        ])
        ->setDisplayConfigurable('view', TRUE)
        // visible by default, we hide them later in hook_install in banner view modes
        ->setDisplayOptions('view', [
          'label' => 'hidden',
        ]);
    }
  }

  return $fields;
}


function ebr_accommodation_form_system_site_information_settings_alter(&$form, $form_state, $form_id) {
  \Drupal::service('ebr.service')->renderRule(
    $form,
    'accommodation',
    t('Accommodation'),
    t('Node types "<code>room</code>" and "<code>package</code>" with field "<code>remote_datasource</code>" filled receive an "@action" action button.', ['@action' => AccommodationBase::getDefaultActionLabel(AccommodationBase::ACTION_ENQUIRY)]),
  );
  \Drupal::service('ebr.service')->renderRule(
    $form,
    'accommodation',
    t('Accommodation'),
    t('Node types "<code>room</code>" and "<code>package</code>" with fields "<code>remote_id</code>" and "<code>remote_datasource</code>" filled receive a "@action" action button.', ['@action' => AccommodationBase::getDefaultActionLabel(AccommodationBase::ACTION_BOOK)]),
  );
}
