<?php

/**
 * @file
 * Main module file.
 */

declare(strict_types=1);

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\ebr_teaser\Entity\TeaserableInterface;
use Drupal\ebr_teaser\Entity\ParagraphTeaserableInterface;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Entity\EntityDisplayRepositoryInterface;
use Drupal\ebr_teaser\Entity\ParagraphTeaserBase;
use Drupal\ebr_teaser\Entity\NodeTeaserBase;
use Drupal\node\Entity\NodeType;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\ebr\Entity\ActionableInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\ebr_teaser\Entity\ReadmoreActionableInterface;
use Drupal\ebr\Entity\ProductableInterface;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function ebr_teaser_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['paragraph']['linkblock'])) {
    $bundles['paragraph']['linkblock']['class'] = ParagraphTeaserBase::class;
  }
  if (isset($bundles['paragraph']['icon'])) {
    $bundles['paragraph']['icon']['class'] = ParagraphTeaserBase::class;
  }

  $fieldManager = \Drupal::service('entity_field.manager');
  /** @var NodeType $bundle */
  foreach (NodeType::loadMultiple() as $bundle) {
    $fieldDefinitions = $fieldManager->getFieldDefinitions('node', $bundle->id());
    // set the default NodeTeaser bundle class if it has the typical teaser fields
    if (isset($bundles['node'][$bundle->id()]) &&
      isset($fieldDefinitions['body']) &&
      isset($fieldDefinitions['field_images']) &&
      isset($fieldDefinitions['field_subtitle']) &&
      // but do not overwrite if a bundle class was already set somewhere else
      !isset($bundles['node'][$bundle->id()]['class'])
    ) {
      $bundles['node'][$bundle->id()]['class'] = NodeTeaserBase::class;
    }
  }
}

/**
 * Replace Drupal's default implementation of "read more" links as extra field.
 *
 * @see ebr_teaser_entity_bundle_field_info()
 * @see \Drupal\ebr_teaser\Entity\NodeReadmoreActionableTrait
 */
function ebr_teaser_entity_extra_field_info_alter(&$info) {
  // Force node title to always be at the top of the list by default.
  foreach (NodeType::loadMultiple() as $bundle) {
    if (isset($info['node'][$bundle->id()]['display']['links'])) {
      unset($info['node'][$bundle->id()]['display']['links']);
    }
  }
}

/**
 * Implements hook_entity_bundle_field_info().
 */
function ebr_teaser_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) {
  $fields = [];

  if ($entity_type->id() == 'node') {
    foreach (NodeTeaserBase::getDefaultActions() as $actionId) {
      $fields[ActionableInterface::ACTION_FIELD_PREFIX . $actionId] = BaseFieldDefinition::create('action_link')
        ->setName(ActionableInterface::ACTION_FIELD_PREFIX . $actionId)
        ->setLabel(t('Action link @type', ['@type' => NodeTeaserBase::getDefaultActionLabel($actionId)]))
        ->setComputed(TRUE)
        ->setClass('\Drupal\ebr\Plugin\Field\SingleComputedItemList')
        ->setSettings([
          'action_type' => $actionId,
        ])
        ->setDisplayConfigurable('view', TRUE)
        // Visible by default, we hide them later in hook_install in banner view modes.
        ->setDisplayOptions('view', [
          'label' => 'hidden',
        ]);
    }
  }

  return $fields;
}

/**
 * Implements hook_preprocess_node().
 */
function ebr_teaser_preprocess_node(&$variables):void {
  _ebr_teaser_prepocess_teaserable_entity($variables, $variables['node']);
}

/**
 * Implements hook_preprocess_paragraph().
 */
function ebr_teaser_preprocess_paragraph(&$variables): void {
  _ebr_teaser_prepocess_teaserable_entity($variables, $variables['paragraph']);
}

/**
 * Shared internal function preprocessing teaserable entities.
 */
function _ebr_teaser_prepocess_teaserable_entity(array &$variables, ContentEntityInterface $entity) {
  if (!$entity instanceof TeaserableInterface) {
    return;
  }
  if (!(($variables['attributes'] ?? []) instanceof Attribute)) {
    $variables['attributes'] = new Attribute($variables['attributes'] ?? []);
  }
  $variables['attributes']->addClass("teaserable");
  $variables['attributes']->addClass("teaserable--view-mode--{$variables['view_mode']}");

  if ($entity instanceof ParagraphTeaserableInterface) {
    $teaserEntity = $entity->getReferencedEntity();
  }
  else {
    $teaserEntity = $entity;
  }
  if (!$teaserEntity instanceof ContentEntityInterface) {
    $variables['attributes']->addClass("teaserable--non-entity");
    return;
  }

  $variables['attributes']->addClass("teaserable--entity--{$teaserEntity->getEntityTypeId()}");
  $variables['attributes']->addClass("teaserable--type--{$teaserEntity->bundle()}");
}

/**
 * Implements hook_entity_view_alter().
 */
function ebr_teaser_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  $viewMode = $build['#view_mode'] ?? EntityDisplayRepositoryInterface::DEFAULT_DISPLAY_MODE;
  if ($entity instanceof TeaserableInterface && $entity->isTeaserableViewmode($viewMode)) {
    if ($entity->getTeaserTitleField() instanceof FieldItemListInterface) {
      $build[$entity->getTeaserTitleField()->getName()] = $entity->getRenderedTeaserTitle($viewMode);
    }
    if ($entity->getTeaserSubtitleField() instanceof FieldItemListInterface) {
      $build[$entity->getTeaserSubtitleField()->getName()] = $entity->getRenderedTeaserSubTitle($viewMode);
    }
    if ($entity->getTeaserImagesField() instanceof FieldItemListInterface) {
      $build[$entity->getTeaserImagesField()->getName()] = $entity->getRenderedTeaserImages($viewMode);
    }
    if ($entity->getTeaserTextField() instanceof FieldItemListInterface) {
      $build[$entity->getTeaserTextField()->getName()] = $entity->getRenderedTeaserText($viewMode);
    }
    if ($entity instanceof ProductableInterface) {
      foreach ($entity->getProductFieldnames($viewMode) as $fieldName) {
        $renderArray = $entity->getRenderedProductField($fieldName, $viewMode);
        if (!empty($renderArray)) {
          $build[$fieldName] = $renderArray;
        }
      }
    }
    if ($entity instanceof ActionableInterface) {
      foreach ($entity->getActionFieldnames($viewMode) as $actionId => $fieldName) {
        $renderArray = $entity->getRenderedAction($actionId, $viewMode);
        if (!empty($renderArray)) {
          $build[$fieldName] = $renderArray;
        }
      }
    }
  }
}

/**
 * Add a set of default CSS classes to all fields.
 */
function ebr_teaser_preprocess_field(&$variables, $hook): void {
  $entity = $variables['element']['#object'];
  if (!(($variables['attributes'] ?? []) instanceof Attribute)) {
    $variables['attributes'] = new Attribute($variables['attributes'] ?? []);
  }

  $viewMode = $variables['element']['#view_mode'];
  if ($entity instanceof TeaserableInterface && $entity->isTeaserableViewmode($viewMode)) {
    // Teaserable entities are additionally labelled with their normalized field name from the interface,
    // which might be different than the actual field name from which the value is retrieved.
    if (isset($variables['element']['#teaser_fieldname'])) {
      $variables['attributes']->addClass("field--teaserable--{$variables['element']['#teaser_fieldname']}");
    }
  }
}
