<?php

/**
 * @file
 * Main module file.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityFormInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\ebr\EntityBusinessrules;

/**
 * Implements hook_entity_base_field_info().
 */
function ebr_internal_notes_entity_base_field_info(EntityTypeInterface $entity_type): array {
  if ($entity_type->id() !== 'node') {
    return [];
  }
  $fields = [];
  $fields[EntityBusinessrules::FIELD_INTERAL_NOTES] = BaseFieldDefinition::create('string_long')
    ->setLabel(t('Internal notes'))
    ->setTranslatable(FALSE)
    ->setRevisionable(TRUE)
    ->setRequired(FALSE)
    ->setDisplayConfigurable('form', FALSE)
    ->setDisplayOptions('form', [
      'region' => 'content',
      'type' => 'string_textarea',
      'settings' => [
        'rows' => 3,
      ],
    ])
    ->setDisplayConfigurable('view', FALSE)
    ->setDisplayOptions('view', [
      'region' => 'hidden',
    ]);
  return $fields;
}

/**
 * Move "internal notes" input field to the sidebar.
 */
function ebr_internal_notes_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  $formObject = $form_state->getFormObject();
  if (!($formObject instanceof EntityFormInterface) || $formObject->getEntity()->getEntityTypeId() !== 'node') {
    return;
  }

  if (array_key_exists(EntityBusinessrules::FIELD_INTERAL_NOTES, $form)) {
    $form[EntityBusinessrules::FIELD_INTERAL_NOTES]['#group'] = 'meta';
  }
}
