system.site:
  type: config_object
  mapping:
    ebr_external_uri:
      type: mapping
      label: 'External action links'
      mapping:
        book:
          type: uri
          label: 'Redirect book node to external URI'
        enquiry:
          type: uri
          label: 'Redirect enquiry node to external URI'
