<?php

/**
 * @file
 * Install, update and uninstall functions.
 */

declare(strict_types = 1);

use Drupal\ebr_accommodation_seekda\Entity\AccommodationSeekda;

/**
 * Implements hook_install().
 */
function ebr_accommodation_seekda_install() {
  $datasource = AccommodationSeekda::DATASOURCE;
  $targetDir = \Drupal::service('file_system')->realpath("public://{$datasource}/") . '/';
  if (!file_exists($targetDir)) {
    mkdir($targetDir, 0775);
  }
  $fieldConfig = \Drupal::entityTypeManager()->getStorage('field_config')->load('node.package.field_subtitle');
  if (!empty($fieldConfig)) {
    $fieldConfig->setSetting('allowed_formats', ['basic_html']);
    $fieldConfig->save();
  }
}

/**
 * Implements hook_uninstall().
 */
function ebr_accommodation_seekda_uninstall(): void {
  $migrations = \Drupal::entityTypeManager()->getStorage('migration')->loadByProperties(['migration_group' => 'seekda']);
  foreach ($migrations as $migration) {
    $migration->delete();
  }
  $migrationGroup = \Drupal::entityTypeManager()->getStorage('migration_group')->load('seekda');
  if ($migrationGroup) {
    $migrationGroup->delete();
  }
}

/**
 * Move all configuration to ebr_accommodation_seekda.settings
 */
function ebr_accommodation_seekda_update_10001(array &$sandbox): ?string {
  $oldConfig = \Drupal::configFactory()->getEditable('system.site');
  if (!empty($oldConfig->get('seekda.property_code'))) {
    $newConfig = \Drupal::configFactory()->getEditable('ebr_accommodation_seekda.settings');
    $newConfig->set('property_code', $oldConfig->get('seekda.property_code'));
    $newConfig->save();
  }
  if (!empty($oldConfig->get('seekda.kube_domain'))) {
    $newConfig = \Drupal::configFactory()->getEditable('ebr_accommodation_seekda.settings');
    $newConfig->set('kube_domain', $oldConfig->get('seekda.kube_domain'));
    $newConfig->save();
  }
  $oldConfig->clear('seekda');
  $oldConfig->save();
  return NULL;
}

