<?php

/**
 * @file
 * Main module file.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\Entity\BaseFieldOverride;
use Drupal\Core\Form\FormStateInterface;
use Drupal\ebr\Entity\WidgetableInterface;
use Drupal\ebr\EntityBusinessrules;
use Drupal\ebr_accommodation\Entity\AccommodationBase;
use Drupal\ebr_accommodation_seekda\Entity\AccommodationSeekda;
use Drupal\ebr_accommodation_seekda\Entity\PackageSeekda;
use Drupal\ebr_accommodation_seekda\Entity\RoomSeekda;
use Drupal\link\LinkItemInterface;
use Drupal\migrate_plus\Entity\MigrationInterface as MigrationEntityInterface;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function ebr_accommodation_seekda_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['node'][AccommodationBase::BUNDLE_ROOM])) {
    $bundles['node'][AccommodationBase::BUNDLE_ROOM]['class'] = RoomSeekda::class;
  }
  if (isset($bundles['node'][AccommodationBase::BUNDLE_PACKAGE])) {
    $bundles['node'][AccommodationBase::BUNDLE_PACKAGE]['class'] = PackageSeekda::class;
  }
}

/**
 * Implements hook_entity_bundle_field_info().
 */
function ebr_accommodation_seekda_entity_bundle_field_info(EntityTypeInterface $entity_type, string $bundle, array $base_field_definitions): array {
  $fields = [];

  // Whether the hook implementation was called for our group type.
  if ($entity_type->id() === 'node' &&
    in_array($bundle, [AccommodationBase::BUNDLE_PACKAGE, AccommodationBase::BUNDLE_ROOM], TRUE) &&
    !empty($base_field_definitions[EntityBusinessrules::FIELD_REMOTE_DATASOURCE])
  ) {
    // Override base ebr_accommodation field.
    $field = BaseFieldOverride::createFromBaseFieldDefinition($base_field_definitions[EntityBusinessrules::FIELD_REMOTE_DATASOURCE], $bundle);
    $field->setDefaultValue(AccommodationSeekda::DATASOURCE);
    $field->setDescription(t('If value is "<code>@remote_datasource</code>", rooms and packages with an "<code>remote_id</code>" receive a booking link.', ['@remote_datasource' => AccommodationSeekda::DATASOURCE]));
    $fields[EntityBusinessrules::FIELD_REMOTE_DATASOURCE] = $field;
  }

  $propertyCode = \Drupal::config('ebr_accommodation_seekda.settings')->get('property_code');

  if ($entity_type->id() === 'node' &&
    $bundle === AccommodationBase::BUNDLE_ROOM &&
    !empty($base_field_definitions[EntityBusinessrules::FIELD_REMOTE_DATASOURCE]) &&
    $propertyCode
  ) {
    $field = BaseFieldOverride::createFromBaseFieldDefinition($base_field_definitions[EntityBusinessrules::FIELD_REMOTE_ID], $bundle);
    $field->setDescription(t('@pms @type ID, see <a href="@url" target="_blank">@short_url</a>',
      [
        '@pms' => AccommodationSeekda::NAME,
        '@type' => \Drupal::entityTypeManager()
          ->getStorage($entity_type->getBundleEntityType())
          ->load($bundle)
          ->label(),
        '@url' => "https://hotels.kognitiv.com/master/hotel/{$propertyCode}/categories",
        '@short_url' => 'hotels.kognitiv.com > Property > Room types',
      ]
    ));
    $fields[EntityBusinessrules::FIELD_REMOTE_ID] = $field;
  }

  if (
    $entity_type->id() === 'node' &&
    $bundle === AccommodationBase::BUNDLE_PACKAGE &&
    !empty($base_field_definitions[EntityBusinessrules::FIELD_REMOTE_DATASOURCE]) &&
    $propertyCode
  ) {
    $field = BaseFieldOverride::createFromBaseFieldDefinition($base_field_definitions[EntityBusinessrules::FIELD_REMOTE_ID], $bundle);
    $field->setDescription(t('@pms @type ID, see <a href="@url" target="_blank">@short_url</a>',
      [
        '@pms' => AccommodationSeekda::NAME,
        '@type' => \Drupal::entityTypeManager()
          ->getStorage($entity_type->getBundleEntityType())
          ->load($bundle)
          ->label(),
        '@url' => "https://hotels.kognitiv.com/master/hotel/{$propertyCode}/offers",
        '@short_url' => 'hotels.kognitiv.com > Marketing > Offers',
      ]
    ));
    $fields[EntityBusinessrules::FIELD_REMOTE_ID] = $field;
  }

  // Seekda rates as flatpickr calendar with prices.
  if ($entity_type->id() === 'node' &&
    in_array($bundle, [AccommodationBase::BUNDLE_ROOM, AccommodationBase::BUNDLE_PACKAGE], TRUE) &&
    !empty($base_field_definitions[EntityBusinessrules::FIELD_REMOTE_DATASOURCE]) &&
    $propertyCode
  ) {
    // Add additional computed fields.
    foreach (AccommodationSeekda::getDefaultWidgets() as $widgetId) {
      $fields[WidgetableInterface::WIDGET_FIELD_PREFIX . $widgetId] = BaseFieldDefinition::create('widget_string')
        ->setName(WidgetableInterface::WIDGET_FIELD_PREFIX . $widgetId)
        ->setLabel(AccommodationSeekda::getDefaultWidgetLabel($widgetId))
        ->setComputed(TRUE)
        ->setClass('\Drupal\ebr\Plugin\Field\SingleComputedItemList')
        ->setDisplayConfigurable('view', TRUE)
        ->setSettings([
          'widget_type' => $widgetId,
        ]);
    }
  }

  return $fields;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ebr_accommodation_seekda_form_system_site_information_settings_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  \Drupal::service('ebr.service')->renderRule(
    $form,
    'accommodation',
    t('Accommodation'),
    t('Node types "<code>room</code>" where field "<code>remote_datasource</code>" is "<code>@remote_datasource</code>", will receive extra fields showing web widgets by @pms.',
      [
        '@remote_datasource' => AccommodationSeekda::DATASOURCE,
        '@pms' => AccommodationSeekda::NAME,
      ]),
  );
  $config = \Drupal::config('ebr_accommodation_seekda.settings');
  $propertyCode = $config->get('property_code');
  $kubeDomain = $config->get('kube_domain');
  $form['seekda'] = [
    '#type' => 'details',
    '#title' => AccommodationSeekda::NAME,
    '#open' => ($propertyCode && $kubeDomain) ? FALSE : TRUE,
    '#tree' => TRUE,
  ];
  $form['seekda']['property_code'] = [
    '#type' => 'textfield',
    '#title' => t('Seekda property code'),
    '#description' => t('You can find your property code at hotels.kognitiv.com, on the top right of the screen, in brackets next to your company name.'),
    '#placeholder' => 'S012345',
    '#pattern' => '[a-zA-Z0-9_\-]+',
    '#required' => TRUE,
    '#config_target' => 'ebr_accommodation_seekda.settings:property_code',
  ];
  $form['seekda']['kube_domain'] = [
    '#type' => 'url',
    '#title' => t('KUBE Domain'),
    '#description' => t('You can find your domain at hotels.kognitiv.com > Booking Engine > Overview > Edit (pencil icon).'),
    '#placeholder' => 'https://booking.your-domain.com',
    '#required' => TRUE,
    '#config_target' => 'ebr_accommodation_seekda.settings:kube_domain',
    '#link_type' => LinkItemInterface::LINK_EXTERNAL,
  ];
  $form['#validate'][] = 'ebr_accommodation_seekda_site_settings_validate';
}

/**
 * Validate form callback for system site settings form.
 */
function ebr_accommodation_seekda_site_settings_validate(array &$form, FormStateInterface $form_state): void {
  $propertyCode = $form_state->getValue(['seekda', 'property_code']);
  $kubeDomain = $form_state->getValue(['seekda', 'kube_domain']);
  if (empty($propertyCode)) {
    $form_state->setErrorByName(
      'seekda][property_code',
      t('@fieldname must not be empty.', ['@fieldname' => t('Seekda property code')])
    );
  }
  if (empty($kubeDomain)) {
    $form_state->setErrorByName(
      'seekda][kube_domain',
      t('@fieldname must not be empty.', ['@fieldname' => t('KUBE Domain')])
    );
    return;
  }
  if (!preg_match('|^[a-zA-Z0-9_\-]+$|', $propertyCode)) {
    $form_state->setErrorByName(
      'seekda][property_code',
      t('In field @label only letters, numbers, underscore and minus are allowed.', ['@label' => t('Seekda property code')]),
    );
  }
  $domain = parse_url($kubeDomain);
  if (($domain['scheme'] ?? '') !== 'https' || empty($domain['host'])) {
    $form_state->setErrorByName(
      'seekda][kube_domain',
      t('@fieldname must be a link in the form of %url',
        [
          '@fieldname' => t('KUBE Domain'),
          '%url' => 'https://sub.domain.com',
        ]
      )
    );
  }
}

/**
 * Implements hook_theme().
 */
function ebr_accommodation_seekda_theme(array $existing, string $type, string $theme, string $path): array {
  $suggestions = [];
  $datasource = AccommodationSeekda::DATASOURCE;
  foreach (AccommodationSeekda::getDefaultWidgets() as $widgetType) {
    $suggestions["{$datasource}_{$widgetType}"] = [
      'variables' => [
        'label' => NULL,
        'widget_type' => $widgetType,
        'entity' => NULL,
        'endpoint' => NULL,
      ],
    ];
  }
  return $suggestions;
}

/**
 * Implements hook_preprocess_HOOK() for seekda_calendar.
 */
function ebr_accommodation_seekda_preprocess_seekda_calendar(array &$variables): void {
  $variables['endpoint'] = \Drupal::service('ebr_accommodation_seekda.seekda')->getCalendarEndpoint();
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function ebr_accommodation_seekda_theme_suggestions_widget_calendar(array $variables): array {
  $node = $variables['entity'];
  $widgetType = $variables['widget_type'];
  $datasource = AccommodationSeekda::DATASOURCE;

  return [
    "{$datasource}_{$widgetType}__{$node->bundle()}",
    "{$datasource}_{$widgetType}__{$node->id()}",
  ];
}

/**
 * Callback function for Migration import (rooms german).
 */
function ebr_accommodation_seekda_migration_100_seekda_rooms_de(): array {
  return _ebr_accommodation_seekda_migration_seekda('de', FALSE);
}

/**
 * Callback function for Migration import (rooms english).
 */
function ebr_accommodation_seekda_migration_110_seekda_rooms_en(): array {
  return _ebr_accommodation_seekda_migration_seekda('en', FALSE);
}

/**
 * Callback function for Migration import (packages german).
 */
function ebr_accommodation_seekda_migration_120_seekda_packages_de(): array {
  return _ebr_accommodation_seekda_migration_seekda('de', TRUE);
}

/**
 * Callback function for Migration import (packages english).
 */
function ebr_accommodation_seekda_migration_130_seekda_packages_en(): array {
  return _ebr_accommodation_seekda_migration_seekda('en', TRUE);
}

/**
 * Returns a personalized endpoint URL for migration import.
 *
 * @internal
 */
function _ebr_accommodation_seekda_migration_seekda(string $langcode, bool $packages = FALSE): array {
  return \Drupal::service('ebr_accommodation_seekda.seekda')->getMigrationUrls($langcode, $packages);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node forms.
 */
function ebr_accommodation_seekda_form_node_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  if (!in_array($form_id, ['node_room_form', 'node_room_edit_form', 'node_package_form', 'node_package_edit_form'], TRUE)) {
    return;
  }
  $node = $form_state->getFormObject()->getEntity();
  if (!$node->get(EntityBusinessrules::FIELD_REMOTE_ID)->value || $node->get(EntityBusinessrules::FIELD_REMOTE_DATASOURCE)->value !== AccommodationSeekda::DATASOURCE) {
    return;
  }
  $migration = match ($node->bundle()) {
    'room' => \Drupal::entityTypeManager()->getStorage('migration')->load('100_seekda_rooms_de'),
    'package' => \Drupal::entityTypeManager()->getStorage('migration')->load('120_seekda_packages_de'),
    default => NULL,
  };
  if (!($migration instanceof MigrationEntityInterface)) {
    return;
  }
  $fields = [];
  foreach ($migration->get('destination')['overwrite_properties'] ?? [] as $fieldName) {
    if ($fieldName === EntityBusinessrules::FIELD_REMOTE_DATASOURCE) {
      continue;
    }
    $fields[] = $node->get($fieldName)->getFieldDefinition()->getLabel();
  }
  if (empty($fields)) {
    return;
  }
  $formIntro['seekda'] = [
    '#type' => 'inline_template',
    '#template' => '<div class="messages messages--status"><p>{{ message }}<br>{{ fields|join(", ") }}</p></div>',
    '#context' => [
      'message' => t(
        'The following fields are imported from <a href=":link" target="_blank">Seekda Channel Manager</a> and must be edited there:',
        [':link' => 'https://hotels.kognitiv.com/']
      ),
      'fields' => $fields,
    ],
  ];
  $form = $formIntro + $form;
}

/**
 * Implements hook_cron().
 */
function ebr_accommodation_seekda_cron(): void {
  \Drupal::service('ebr_accommodation_seekda.cron')->run();
}
