<?php

declare(strict_types=1);

/**
 * @file
 * Main module file.
 */

use Drupal\Core\Entity\EntityFormInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\ebr_stable_media\Plugin\Derivative\StableMediaEditLinkDeriver;

/**
 * Implements hook_page_attachments_alter().
 */
function ebr_stable_media_page_attachments_alter(&$page): void {
  if (function_exists('_gin_toolbar_gin_is_active') && _gin_toolbar_gin_is_active()) {
    $page['#attached']['library'][] = 'ebr_stable_media/toolbar';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ebr_stable_media_form_system_site_information_settings_alter(&$form, $form_state, $form_id): void {
  \Drupal::service('ebr.service')->renderRule(
    $form,
    'stable_media_link',
    t('Media permalinks'),
    t(
      'Media entities where field "<code>internal_id</code>" starts with "<code>@prefix</code>" generate a link in the editor menu.',
      ['@prefix' => StableMediaEditLinkDeriver::STABLE_MEDIA_PREFIX]
    ),

  );
  \Drupal::service('ebr.service')->renderRule(
    $form,
    'stable_media_link',
    t('Media permalinks'),
    t('A hint how to use those permalinks is shown in the media edit form.'),
  );
}

/**
 * Implements hook_form_alter().
 */
function ebr_stable_media_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  if (!($form_state->getFormObject() instanceof EntityFormInterface)) {
    return;
  }
  $entity = $form_state->getFormObject()->getEntity();
  if ($form_id !== "media_{$entity->bundle()}_edit_form") {
    return;
  }
  if (!$entity->hasField('internal_id') ||
    $entity->get('internal_id')->isEmpty() ||
    !str_starts_with($entity->get('internal_id')->value, StableMediaEditLinkDeriver::STABLE_MEDIA_PREFIX)
  ) {
    return;
  }

  $message = [
    '#theme' => 'status_messages',
    '#message_list' => [
      'info' => [
        // phpcs:disable
        t("Use the URL <span class=\"select-all inline-block border border-current border-solid px-1 nowrap \">@url</span> to create permalinks to this document. Permalinks never change, even after uploading a new file.",
          ['@url' => "/media/{$entity->id()}/download?inline"],
        ),
        // phpcs:enable
      ],
    ],
  ];

  array_unshift($form, $message);
}
